config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :snippets do
    resources :stamps, only: [:index, :create]
  end
  resources :stamps, only: [:update, :destroy]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root 'snippets#new'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  has_many :stamps
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
  belongs_to :snippet
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true,
  format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
  
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def new
    @snippet = Snippet.new
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :find_snippet, only: [:index, :create]

  def index
    render json: @snippet.stamps
  end

  def create
    @stamp = @snippet.stamps.build(stamp_params)
    respond_to do |format|
      if @stamp.save
        format.json { render json: @stamp }
      else
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @stamp = Stamp.find(params[:id])
    if @stamp.update(stamp_params)
      render json: @stamp
    end
  end

  def destroy
    @stamp = Stamp.find(params[:id])
    @stamp.destroy
    render json: @stamp
  end

  private
    def stamp_params
      params.permit().tap do |whitelisted|
        whitelisted[:state] = params[:state]
      end
    end

    def find_snippet
      @snippet = Snippet.find(params[:snippet_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codestamps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <nav class='navbar navbar top fixed'>
      <div class='container'>
        <div class="navbar-header">
          <div class="navbar-brand pull-left">
            <%= image_tag('logo.png', class: 'logo', width: '30%') %>
          </div>
        </div>
        <ul class='nav navbar-nav pull-right'>
          <li><%= link_to 'home', root_path %></li>
          <li><%= link_to 'new user', new_user_path %></li>
          <li><%= link_to 'new snippet', new_snippet_path %></li>
          <% if user_signed_in? %>
            <li>Hello <%= current_user.full_name %>,</li>
            <li><%= link_to "logout", sessions_path, method: :delete,
            data: {confirm: "are you sure you want to log out?"}%></li>
          <% else %>
            <li><%= link_to "login", new_session_path %></li>
            <li><%= link_to "sign Up", new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

    <%= yield %>

  <div class="navbar navbar-default navbar-fixed-bottom">
      <div class="container-fluid">
        <p class="navbar-text pull-left">© 2016 - codestamps Built By Ryan Ching.
          <a href="https://ca.linkedin.com/in/ryching">Linkedin</a>
        </p>

        <a href="https://github.com/ryancj/codestamps" class="navbar-btn btn-danger btn pull-right footer-button">
        <span class="glyphicon glyphicon-star"></span>Github Link</a>
      </div>
    </div>
  </body>
</html>

app/views/snippets/new.html.erb
<%= react_component('Editor', theme: @snippet.theme, codeBlock: @snippet.codeblock, snippet_id: @snippet.id, stamps: @snippet.stamps.map{|stamp| StampSerializer.new(stamp).serializable_hash}) %>
<a href='http://localhost:3000/snippets/1'><button class='btn btn-sm btn-success glyphicon glyphicon-plus'></button></a>

app/views/snippets/show.html.erb
<div class="container-fluid">
  <%= react_component('Editor', theme: @snippet.theme, codeBlock: @snippet.codeblock, snippet_id: @snippet.id, stamps: @snippet.stamps.map{|stamp| StampSerializer.new(stamp).serializable_hash}) %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>